
export const pathConstants = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  RESET_PASSWORD: "/forget-password",
  LOGIN_OTP_VERIFICATION: "/login-otp-verification",
  AUTH_CALLBACK : "/auth/callback",
  RESET_PASSWORD_CALLBACK: "/reset-password/callback",
  SUPER_ADMIN_DASHBOARD: "/super-admin-dashboard",
  ADMIN_DASHBOARD: "/admin-dashboard",
  CANDIDATE_DASHBOARD: "/candidate-dashboard",
  ALL_CANDIDATES: "/all-candidates",
  UPDATE_CANDIDATE: ({candidateId}) => `/update-candidate/${candidateId}`,  
  CREATE_ASSESSMENT: "/create-assessment",
  CREATE_SCHOOL: "/create-school",
  CREATE_CANDIDATE: "/create-candidate",
  SUPER_ADMIN_USER: "/super-admin-user",
  QUESTION: "question",
  CLASS: "/class-management",
  ALL_CLASSES: "/all-classes",
  CREATE_CLASS: "/create-class",
  UPDATE_CLASS:({classId}) => `/update-class/${classId}`,
  UPDATE_SUBJECT: ({subjectId}) => `/update-subject/${subjectId}`,
  SUBJECT: "/subject",
  CREATE_SUBJECT: "/create-subject",
  ALL_SUBJECTS: "/all-subjects",
  CANDIDATE: "/candidates",
  RESULT: "/result",
  EXAMS: "/exams",
  ADD_QUESTION: "add-question",
  QUESTION_CATEGORIES: "question-categories",
  ALL_QUESTION: "all-question",
  QUESTION_TYPE: "question-type",
  CANDIDATE_EXAM: "/candidate-exam",
  CANDIDATE_RESULT: "candidate-result",
  SETTINGS: "/settings",
  REWARDS: "/rewardHub",
  AJO: "/ajo",
  SAVINGS: "/savings",
  LOAN: "/loan",
  DISCOVER: "/discover",

};
