
export const pathConstants = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  RESET_PASSWORD: "/forget-password",
  LOGIN_OTP_VERIFICATION: "/login-otp-verification",
  AUTH_CALLBACK : "/auth/callback",
  RESET_PASSWORD_CALLBACK: "/reset-password/callback",

  ADMIN_DASHBOARD: "/admin_dashboard",
  CANDIDATE_DASHBOARD: "/candidate_dashboard",
  CREATE_ASSESSMENT: "/create_assessment",
  QUESTION: "question",
  CANDIDATE: "/candidates",
  RESULT: "/result",
  EXAMS: "/exams",
  ADD_QUESTION: "add_question",
  QUESTION_CATEGORIES: "question_categories",
  ALL_QUESTION: "all_question",
  QUESTION_TYPE: "question_type",
  CANDIDATE_EXAM: "/candidate_exam",
  CANDIDATE_RESULT: "candidate_result",
  SETTINGS: "/settings",
  REWARDS: "/rewardHub",
  AJO: "/ajo",
  SAVINGS: "/savings",
  LOAN: "/loan",
  DISCOVER: "/discover",

};
